
version: "3.9"
services:
  backend:
    build: .
    environment:
      - "CFG_PATH=/config/conf.json"
      - "TRANSFORMERS_CACHE=/config/transformers"
    ports:
      - "8080:8080"
    volumes:
    - ./config:/config
    networks:
      - app_network
  database:
    image: "mongo"
    environment:
      - "MONGO_INITDB_DATABASE=db"
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge